language: java
jdk:
  - oraclejdk7
  - openjdk7

before_install:

 - pwd
 - ls  
 - wget -P "/home/travis/build/LaInerteBarraDeCarbon/jrpg-2017a-servidor/" https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
 - chmod +x gradlew
- git clone https://github.com/LaInerteBarraDeCarbon/jrpg-2017a-cliente.git /home/travis/build/LaInerteBarraDeCarbon/jrpg-2017a-cliente
